version: '3.8'

services:

  php81-apache:
    build: ./php8
    image: php:8.1-apache
    container_name: php81-mobile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    ports:
      - "5802:80"
    depends_on:
      - mysql80
  
  php81-websocket:
    build: ./websocket_server
    image: php:8.1-cli
    container_name: websocket-mobile
    volumes:
      - ./websocket_server:/var/www/html
    working_dir: /var/www/html
    ports:
      - "5803:5803"
    depends_on:
      - mysql80
  
  adminer:
    image: adminer
    container_name: adminer-mobile
    environment:
      PMA_HOST: mysql80
      PMA_USER: user
      PMA_PASSWORD: userpass
      PMA_DATABASE: db
    ports:
      - "5805:8080"
    depends_on:
      - mysql80
  
  mysql80:
    image: mysql:8.0
    container_name: mysql80-mobile
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpass
      - TZ=America/Sao_Paulo
    ports:
      - "3358:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
  
  # flutter-dart:
  #     build: ./mobile
  #     image: dart:stable
  #     container_name: flutter-dart
  #     volumes:
  #       - ./mobile:/app
  #     ports:
  #       - "5801:8080"

volumes:
  mysql-data:
